name: Release
on:
  release:
    types: [created]
jobs:
  call_npm_release:
    uses: szikszail/workflows/.github/workflows/npm-release.yml@main
    with:
      dist_folder: '.'
    secrets:
      npm_token: ${{ secrets.npm_token }}